jc=javac
JFLAGS = -Xlint

all: Car.class Node.class NodeComparator.class ParkingEspace.class Parser.class QueueManager.class Solver.class

Car.class: Car.java
	$(jc) $(CFLAGS) Car.java 

Node.class: Node.java
	$(jc) $(CFLAGS) Node.java

NodeComparator.class: NodeComparator.java
	$(jc) $(CFLAGS) NodeComparator.java 

ParkingEspace.class: ParkingEspace.java
	$(jc) $(CFLAGS) ParkingEspace.java 

Parser.class: Parser.java
	$(jc) $(CFLAGS) Parser.java

QueueManager.class: QueueManager.java
	$(jc) $(CFLAGS) QueueManager.java 

Solver.class: Solver.java
	$(jc) $(CFLAGS) Solver.java 
